### ISSUE TITLE
investigate Knowi

### ISSUE THREAD

**Issue by batmany13** [SYNQfm/synq-ui#1]
We spoke with Head of Product at [knowi.com](https://knowi.com/), and they do visualization on top of data, and I think coudl use something like that.  They are like a fancier version of metabase and its hosted.  One of the key features they have is the ability to aggregate data from multiple sources, so they can read multiple databases, APIs, Google Analytics, NoSQL and then join it together.  They also let you white label their UI so we could just embed that and let users customize their view.  We actually have a test login thats registered in 1password.  We can also put you in touch with Lorraine who can do a demo for you

**Comment by JulianNymark** [comment]
a discussion came up related to this between Halvard and me. It was in regards to migrating the `cdn_events` table to a more longterm / scalable solution (it's going to have to be moved out of obaku at some point, preferably before it blows up in size, and queries on cdn data become unbearably slow, VACUUM no longer works due to running out of disk space... etc  :p ).

The reason this is related is that both the tools we are looking at to replace metabase: `KNOWI` and `Periscope` seem to be fine with multiple data sources / multiple db connections, and querying on data across them. This could dictate the _how_ we move the table `cdn_events` table out from obaku.

here are 2 ideas for how to migrate the table to e.g. amazon redshift.

One idea was to do everything 'seamlessly' in postgres, where we connect to a redshift db using postgres FDW and dblink. Making old queries behave _superficially_ as if `cdn_events` was still a table on obaku. (this option requires more postgres work, but shouldn't require any changes to metabase or the importer, or potentially other programs that touch the `cdn_events` table). https://aws.amazon.com/blogs/big-data/join-amazon-redshift-and-amazon-rds-postgresql-with-dblink/

Another idea was to duplicate our datasets during the transition period (until we then either decide to drop metabase entirely, and therefore are not required to maintain the `cdn_events` table at obaku at all). This option requires us to touch the `cdnlog_parse` program (it has to connect to 2 databases, and do 2 inserts).

no cdn log data 'migration' should become an issue, as we support re-ingesting all our cdn data. (since we store the entirety of our cdn logs on s3)

**Comment by halvardos** [comment]
After a quick search for alternatives it looks like the other competitors are lacking on the multiple data sources features that both periscope and knowi supports.
I think that is an essential feature for us.

**Comment by batmany13** [comment]
@JulianNymark It seems like we can just treat them as two databases without doing too much.  If we just created an user that only had access to the cdn events, and then keep the "readonly" user we have setup (to access all of obaku), we can probably create the right tables and views assuming that they are in two different data stores.  Then, we could change our backend whenever we want.  The other option is just to run a parallel project and just work on data insertion into redshift (or something like it) and while it would require us to do "dual data sets", this also allows us to just leave obaku as is, and then peel off the stats whenever redshift is ready.  Then we can just build knowi/periscope assuming these two data sets.

As for redshfit vs other data management tools, is there something specific redshift will give us that is vaulable over other data stores?

**Comment by batmany13** [comment]
the initial research has been done and we're testing with Knowi now.  Work can be found in [doppelganger](https://github.com/SYNQfm/doppelganger)
